Persist the web app's storage folder
fly-apps/fly-laravel pull request #48
Opened 2023-06-05 21:06 UTC by KTanAug21

Create a volume service class:
1. Prompts whether user wants to persist the storage folder
2. Includes mount in the fly.toml array
3. Creates a .fly script to restore storage content ( since mounting a volume to the folder initially erases its content )
4. Backs up storage to storage_ folder( used in the .fly script to restore storage folder )
5. Deletes storage_ folder locally during deploy

2023-06-12 15:05 UTC, Johannes-Werbrouck requested changes
A lot has changed in the main branch, sorry for that !😅 
Please merge the main branch into your branch and check my comments, some small changes will be needed. Thanks!

2023-06-12 15:05 UTC, Johannes-Werbrouck commented on app/Commands/LaunchCommand.php
> +                $mount = $volumeService->promptVolume( $appName );
The main branch has seen a lot of changes, one of them is that the handle method is split up in an `input...` and a `setUp...` method for every LaunchCommand. This way, all the user input can be consolidated in the `input...` method, and used later on to set everything up in the `setUp...` method. Could you please follow this logic here as well?

2023-06-12 15:05 UTC, Johannes-Werbrouck commented on app/Services/VolumeService.php
> +        $answer = $this->command->choice(
you could use `$this->command->confirm()` here instead of `->choice()`

2023-06-12 16:54 UTC, KTanAug21 commented
> A lot has changed in the main branch, sorry for that !😅 Please merge the main branch into your branch and check my comments, some small changes will be needed. Thanks!

You've done an amazing job cleaning and adding new features to fly-laravel! ✨No worries on that! 

Also, I'm planning on adding tests to existing features in the fly-laravel package, so I'm not sure yet whether I'll finalize this PR or those tests first. Don't know which one I'll work on first, but I'll just finalize an article for this week and get back to the fly-laravel package.

Awesome job so far @Johannes-Werbrouck!

2023-09-25 13:37 UTC, fideloper commented
Another thing someone mentioned to me in a youtube comment is that some people symlink `public/storage` to `storage/app/public` (or similar), which works with the [`storage:link`](https://laravel.com/docs/10.x/filesystem#the-public-disk) command.

I wonder if the `storage:link` command is one we could add in the `.fly/scripts` command as well.

(I don't think there are negative consequences to assuming this command can be run on every deploy, but LMK if you think of any)

2023-11-08 14:04 UTC, closed without merging